# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('has_header', models.BooleanField(default=True, editable=False)),
                ('header', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('csv_file', models.FileField(editable=False, upload_to='api/csvs/')),
            ],
            options={
                'ordering': ('uploaded',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ImageField(upload_to='api/images/')),
            ],
            options={
                'ordering': ('uploaded',),
            },
        ),
    ]
