# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170324_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('resized_file', models.ImageField(upload_to='api/images/')),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='original_url',
        ),
        migrations.AlterField(
            model_name='csv',
            name='header',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
        migrations.AddField(
            model_name='resizedimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
