# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170325_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(default='jpg', max_length=10),
            preserve_default=False,
        ),
    ]
