# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='original_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='original_url',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='resizedimage',
            old_name='resized_file',
            new_name='file',
        ),
    ]
